services:
  backend-server:
    build: ./server
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://mysql-db:3306/store
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_FLYWAY_ENABLED: ${SPRING_FLYWAY_ENABLED}
    networks:
      - local-network
  mysql-db:
    image: mysql:9.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: store
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - local-network

volumes:
  db-data:

networks:
  local-network:
    driver: bridge
